### ISSUE TITLE
On Windows: docker.exe: Error response from daemon: invalid volume specification

### ISSUE THREAD

**Issue by keneo** [Games-and-Simulations/sc-docker#15]
### expected behaviour
game starts
### actual behaviour
game does not start
### steps to reproduce
```

C:\Users\barte\dev\learn\ml\sc-docker
λ scbw.play --bots krasi0 CherryPi --headless --log_level=DEBUG
INFO checking docker version
DEBUG Using docker API version b"'1.35'\n"
INFO checking docker can run
INFO checking docker has network sc_net
DEBUG docker network id: b'77620c97881e\n'
INFO checking if there is local image starcraft:game
DEBUG docker image id: b'f8d4b4058c9d\n'
DEBUG checking bot in C:\Users\barte\AppData\Roaming/scbw/bots/krasi0
DEBUG found bot in C:\Users\barte\AppData\Roaming/scbw/bots/krasi0
DEBUG checking bot in C:\Users\barte\AppData\Roaming/scbw/bots/CherryPi
DEBUG found bot in C:\Users\barte\AppData\Roaming/scbw/bots/CherryPi
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_C5AF6D72_0_krasi0', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/logs:/app/logs:rw', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/bots:/app/bots:ro', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/maps:/app/sc/maps:rw', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '--volume', 'C:\\Users\\barte\\AppData\\Roaming/scbw/bots/krasi0/write/GAME_C5AF6D72_0:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=krasi0', '-e', 'PLAYER_RACE=T', '-e', 'NTH_PLAYER=0', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_C5AF6D72', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=krasi0', '-e', 'BOT_FILE=krasi0AIClient.exe', 'starcraft:game', '/app/play_bot.sh', '--game', 'GAME_C5AF6D72', '--name', 'krasi0', '--race', 'T', '--lan', '--host', '--map', '/app/sc/maps/sscai/(2)Benzene.scx']
C:\Users\barte\scoop\apps\docker\current\docker.exe: Error response from daemon: invalid volume specification: 'C:\Users\barte\AppData\Roaming/scbw/maps:/app/sc/maps:rw'.
See 'C:\Users\barte\scoop\apps\docker\current\docker.exe run --help'.
ERROR could not launch BotPlayer:krasi0:T in container GAME_C5AF6D72_0_krasi0
Traceback (most recent call last):
  File "c:\users\barte\scoop\apps\python\3.6.3\lib\site-packages\scbw\cli.py", line 134, in main
    game_result = run_game(args)
  File "c:\users\barte\scoop\apps\python\3.6.3\lib\site-packages\scbw\game.py", line 150, in run_game
    launch_game(players, launch_params, args.show_all, args.read_overwrite, wait_callback)
  File "c:\users\barte\scoop\apps\python\3.6.3\lib\site-packages\scbw\docker.py", line 307, in launch_game
    launch_image(player, nth_player=i, num_players=len(players), **launch_params)
  File "c:\users\barte\scoop\apps\python\3.6.3\lib\site-packages\scbw\docker.py", line 288, in launch_image
    f"could not launch {player} in container {game_name}_{nth_player}_{player.name}")
scbw.error.DockerException: could not launch BotPlayer:krasi0:T in container GAME_C5AF6D72_0_krasi0

C:\Users\barte\dev\learn\ml\sc-docker
λ

```

### operating system

    win (version)
   
### docker version

output of command `docker version`:
```

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      18.01.0-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   03596f5
 Built:        Wed Jan 10 20:13:12 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

### scbw version

output of command `scbw.play -v`

`0.2a19
`

**Comment by kant2002** [comment]
Could you check that you share you C drive in Docker. See notes: https://github.com/Games-and-Simulations/sc-docker/blob/master/INSTALL.md#docker-1

**Comment by keneo** [comment]
Thx @kant2002 . I'm not using "docker for windows", but a plain docker instead (`scoop install docker`) . Hello world works fine. Is there a hope for me without switching docker distribution? ;)

**Comment by michalsustr** [comment]
I don't have win around here right now to test. 

Does `C:\Users\barte\AppData\Roaming/scbw/map` exist, and is it allowed as mountable volume?

Maybe mix of slashes is a problem.
This seems related: https://github.com/docker/toolbox/issues/607#issuecomment-287048316

**Comment by MicroDK** [comment]
I had the same error, but the error was resolved by sharing the C drive.

**Comment by michalsustr** [comment]
I'm going to assume https://github.com/Games-and-Simulations/sc-docker/issues/18 solves this as well, I'll publish new version soon.
