### ISSUE TITLE
WARNING Could not find the bot 'krasi0' on SSCAIT server

### ISSUE THREAD

**Issue by nlinker** [Games-and-Simulations/sc-docker#23]
### expected behaviour

The command 
```
(scbw) ~/t/scbw ❯❯❯ scbw.play --bots "krasi0" "CherryPi" --show_all                                                                                                   
```
should run successfully

### actual behaviour

```
(scbw) ~/t/scbw ❯❯❯ scbw.play --bots "krasi0" "CherryPi" --show_all
ERROR the JSON object must be str, not 'bytes'
```

### steps to reproduce

```
(scbw) ~/t/scbw ❯❯❯ scbw.play --bots "krasi0" "CherryPi" --show_all --log_level=DEBUG                                                                                 ⏎
DEBUG checking bot in /home/nick/.scbw/bots/krasi0
DEBUG Starting new HTTP connection (1): sscaitournament.com
DEBUG http://sscaitournament.com:80 "GET /api/bots.php HTTP/1.1" 301 None
DEBUG Starting new HTTPS connection (1): sscaitournament.com
DEBUG https://sscaitournament.com:443 "GET /api/bots.php HTTP/1.1" 200 None
ERROR the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/nick/tmp/scbw/lib/python3.5/site-packages/scbw/bot_storage.py", line 40, in find_bot
    bots = self.get_bot_specs()
  File "/home/nick/tmp/scbw/lib/python3.5/site-packages/scbw/bot_storage.py", line 83, in get_bot_specs
    return json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
WARNING Could not find the bot 'krasi0' on SSCAIT server
Traceback (most recent call last):
  File "/home/nick/tmp/scbw/bin/scbw.play", line 11, in <module>
    sys.exit(main())
  File "/home/nick/tmp/scbw/lib/python3.5/site-packages/scbw/cli.py", line 178, in main
    game_result = run_game(args)
  File "/home/nick/tmp/scbw/lib/python3.5/site-packages/scbw/game.py", line 87, in run_game
    players += retrieve_bots(args.bots, bot_storages)
  File "/home/nick/tmp/scbw/lib/python3.5/site-packages/scbw/bot_factory.py", line 17, in retrieve_bots
    raise Exception(('Could not find bot %s' % (bot_name, )))
Exception: Could not find bot krasi0
```

### operating system

Ubuntu `lsb_release -a`:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

### docker version

output of command `docker version`:

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

### scbw version

output of command `scbw.play -v`

0.2b2

**Comment by michalsustr** [comment]
Will use `response.text`, as it is suggested for this use case : http://docs.python-requests.org/en/master/user/quickstart/#response-content

Thanks!

Will update soon with newer version.

**Comment by nlinker** [comment]
Hi, @michalsustr, thanks for the feedback!

I digged some time, probably even more solid is to use `response.json()`.
http://docs.python-requests.org/en/master/user/quickstart/#json-response-content

HTH
