### ISSUE TITLE
Some containers exited prematurely, please check logs

### ISSUE THREAD

**Issue by haopan27** [Games-and-Simulations/sc-docker#36]
### expected behaviour
The game is launched properly

### actual behaviour
![image](https://user-images.githubusercontent.com/22966043/36324866-d3fd6cce-1323-11e8-9cd3-6ba5b510750f.png)

### steps to reproduce
In PowerShell, type either
1) scbw.play --bots Iron Hao --headless --read_overwrite
or
2) scbw.play --bots Iron Hao --headless

Please run the command issued with  `--log_level=DEBUG --log_verbose` parameters and log:
**scbw.play --bots Iron Hao --headless --log_level=DEBUG --log_verbose**
    usage: scbw.play.exe [-h] [--install] [--bots BOT_NAME[:RACE] [BOT_NAME[:RACE]
                     ...]] [--human] [--map MAP.scx] [--headless]
                     [--game_name GAME_NAME] [--game_type GAME_TYPE]
                     [--game_speed GAME_SPEED] [--timeout TIMEOUT]
                     [--bot_dir BOT_DIR] [--log_dir LOG_DIR]
                     [--map_dir MAP_DIR]
                     [--bwapi_data_bwta_dir BWAPI_DATA_BWTA_DIR]
                     [--bwapi_data_bwta2_dir BWAPI_DATA_BWTA2_DIR]
                     [--vnc_base_port VNC_BASE_PORT] [--show_all]
                     [--log_level {DEBUG,INFO,WARN,ERROR}] [--read_overwrite]
                     [--docker_image DOCKER_IMAGE] [--opt OPT]
                     [--disable_checks] [-v]
scbw.play.exe: error: unrecognized arguments: --log_verbose

Then I did this: 
**scbw.play --bots Iron Hao --headless --log_level=DEBUG**
 checking bot in C:\Users\fractal\AppData\Roaming/scbw/bots/Iron
DEBUG Starting new HTTP connection (1): sscaitournament.com
DEBUG http://sscaitournament.com:80 "GET /api/bots.php HTTP/1.1" 301 None
DEBUG Starting new HTTPS connection (1): sscaitournament.com
DEBUG https://sscaitournament.com:443 "GET /api/bots.php HTTP/1.1" 200 None
INFO Could not find Iron, trying to find closest match in 188 available bots
INFO Found these bots:
INFO 0: Stone
INFO 1: If Bot
INFO 2: Iron bot
INFO 3: AILien
INFO 4: Korean
INFO Which would you like to use? (enter number 0-4)
2
DEBUG checking bot in C:\Users\fractal\AppData\Roaming/scbw/bots/Hao
DEBUG Starting new HTTP connection (1): sscaitournament.com
DEBUG http://sscaitournament.com:80 "GET /api/bots.php HTTP/1.1" 301 None
DEBUG Starting new HTTPS connection (1): sscaitournament.com
DEBUG https://sscaitournament.com:443 "GET /api/bots.php HTTP/1.1" 200 None
INFO Could not find Hao, trying to find closest match in 188 available bots
INFO Found these bots:
INFO 0: Flash
INFO 1: Hao Pan
INFO 2: ggBot
INFO 3: Stone
INFO 4: krasi0
INFO Which would you like to use? (enter number 0-4)
1
DEBUG ['docker', 'run', '-d', '--privileged', '--name', 'GAME_512331E8_0_Iron_bot', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/logs:/app/logs:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bots:/app/bots:ro', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/maps:/app/sc/maps:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bots/Iron bot/write/GAME_512331E8_0:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=Iron bot', '-e', 'PLAYER_RACE=T', '-e', 'NTH_PLAYER=0', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_512331E8', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=Iron bot', '-e', 'BOT_FILE=Iron.dll', '-e', 'BOT_BWAPI=4.1.2', '-e', 'TM_LOG_RESULTS=../logs/GAME_512331E8_0_results.json', '-e', 'TM_LOG_FRAMETIMES=../logs/GAME_512331E8_0_frames.csv', 'starcraft:game', '/app/play_bot.sh', '--game', 'GAME_512331E8', '--name', 'Iron bot', '--race', 'T', '--lan', '--host', '--map', '/app/sc/maps/sscai/(2)Benzene.scx']
INFO launched BotPlayer:Iron bot:T in container GAME_512331E8_0_Iron bot
DEBUG ['docker', 'run', '-d', '--privileged', '--name', 'GAME_512331E8_1_Hao_Pan', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/logs:/app/logs:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bots:/app/bots:ro', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/maps:/app/sc/maps:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '--volume', '//c/Users/fractal/AppData/Roaming/scbw/bots/Hao Pan/write/GAME_512331E8_1:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=Hao Pan', '-e', 'PLAYER_RACE=T', '-e', 'NTH_PLAYER=1', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_512331E8', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=Hao Pan', '-e', 'BOT_FILE=Halo.dll', '-e', 'BOT_BWAPI=4.1.2', '-e', 'TM_LOG_RESULTS=../logs/GAME_512331E8_1_results.json', '-e', 'TM_LOG_FRAMETIMES=../logs/GAME_512331E8_1_frames.csv', 'starcraft:game', '/app/play_bot.sh', '--game', 'GAME_512331E8', '--name', 'Hao Pan', '--race', 'T', '--lan', '--join']
INFO launched BotPlayer:Hao Pan:T in container GAME_512331E8_1_Hao Pan
INFO Checking if game has launched properly...
DEBUG running containers: []
ERROR Some containers exited prematurely, please check logs
Traceback (most recent call last):
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\cli.py", line 178, in main
    game_result = run_game(args)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\game.py", line 90, in run_game
    wait_callback)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\docker.py", line 343, in launch_game
    'Some containers exited prematurely, please check logs')
scbw.error.DockerException: Some containers exited prematurely, please check logs

### operating system

    win (Windows 10 Pro)

Ubuntu `lsb_release -a`:

### docker version

output of command `docker version`:

   Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

### scbw version

output of command `scbw.play -v`

    0.2b3

By the way, I am aware of a recent update regarding my previous issue 'Where is the read folder?'. Thanks for the speedy solution, I didn't have the chance to say 'thanks' yet 👍 

Anyway, I thought I need to update my installation. So I tried
pip install scbw==0.2b4
scbw.play --install
And got the following error message:
Traceback (most recent call last):
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fractal\AppData\Local\Programs\Python\Python36\Scripts\scbw.play.exe\__main__.py", line 5, in <module>
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\__init__.py", line 2, in <module>
    from .game import run_game, GameResult, GameArgs
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\game.py", line 13, in <module>
    from .plot import RealtimeFramePlotter
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\plot.py", line 1, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

So I reverted back to 0.2b3. All the stuff reported above is based on this version (0.2b3).

**Comment by michalsustr** [comment]
I just realized when I left work that I forgot to put new dependencies to the library :man_facepalming: 
I guess it's really a time to make some build server that would make automated integration tests to prevent trivial missteps like this in the future.

Sorry :) can you try `0.2b5` ?

**Comment by MicroDK** [comment]
with version 0.2b6 (docker-machine workaround):

`scbw.play --bots "CherryPi" "Marian Devecka" --show_all --read_overwrite --game_speed 10 --vnc_host localhost --log_level=DEBUG --log_verbose`

2018-02-16 22:41:45 DEBUG scbw.bot_storage[7389] checking bot in /Users/micky/.scbw/bots/CherryPi
2018-02-16 22:41:45 DEBUG scbw.bot_storage[7389] found bot in /Users/micky/.scbw/bots/CherryPi
2018-02-16 22:41:45 DEBUG scbw.bot_storage[7389] checking bot in /Users/micky/.scbw/bots/Marian Devecka
2018-02-16 22:41:45 DEBUG scbw.bot_storage[7389] found bot in /Users/micky/.scbw/bots/Marian Devecka
2018-02-16 22:41:45 DEBUG scbw.docker[7389] 'docker' 'run' '-d' '--privileged' '--name' 'GAME_C764DACE_0_CherryPi' '--volume' '/Users/micky/.scbw/logs:/app/logs:rw' '--volume' '/Users/micky/.scbw/bots:/app/bots:ro' '--volume' '/Users/micky/.scbw/maps:/app/sc/maps:rw' '--volume' '/Users/micky/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw' '--volume' '/Users/micky/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw' '--net' 'sc_net' '-p' '5900:5900' '--volume' '/Users/micky/.scbw/bots/CherryPi/write/GAME_C764DACE_0:/app/sc/bwapi-data/write:rw' '--volume' '/Users/micky/.scbw/bots/CherryPi/read/:/app/sc/bwapi-data/read:rw' '-e' 'PLAYER_NAME=CherryPi' '-e' 'PLAYER_RACE=Z' '-e' 'NTH_PLAYER=0' '-e' 'NUM_PLAYERS=2' '-e' 'GAME_NAME=GAME_C764DACE' '-e' 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx' '-e' 'GAME_TYPE=FREE_FOR_ALL' '-e' 'SPEED_OVERRIDE=10' '-e' 'HIDE_NAMES=0' '-e' 'TM_LOG_RESULTS=../logs/GAME_C764DACE_0_results.json' '-e' 'TM_LOG_FRAMETIMES=../logs/GAME_C764DACE_0_frames.csv' '-e' 'TM_SPEED_OVERRIDE=10' '-e' 'TM_ALLOW_USER_INPUT=0' '-e' 'EXIT_CODE_REALTIME_OUTED=2' '-e' 'BOT_NAME=CherryPi' '-e' 'BOT_FILE=BWEnv.dll' '-e' 'BOT_BWAPI=4.2.0' 'starcraft:game' '/app/play_bot.sh' '--headful'
2018-02-16 22:41:45 INFO scbw.docker[7389] launched BotPlayer:CherryPi:Z
2018-02-16 22:41:45 DEBUG scbw.docker[7389] container name 'GAME_C764DACE_0_CherryPi'
2018-02-16 22:41:45 DEBUG scbw.docker[7389] container id '3bd3b436525c'
2018-02-16 22:41:45 DEBUG scbw.docker[7389] 'docker' 'run' '-d' '--privileged' '--name' 'GAME_C764DACE_1_Marian_Devecka' '--volume' '/Users/micky/.scbw/logs:/app/logs:rw' '--volume' '/Users/micky/.scbw/bots:/app/bots:ro' '--volume' '/Users/micky/.scbw/maps:/app/sc/maps:rw' '--volume' '/Users/micky/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw' '--volume' '/Users/micky/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw' '--net' 'sc_net' '-p' '5901:5900' '--volume' '/Users/micky/.scbw/bots/Marian Devecka/write/GAME_C764DACE_1:/app/sc/bwapi-data/write:rw' '--volume' '/Users/micky/.scbw/bots/Marian Devecka/read/:/app/sc/bwapi-data/read:rw' '-e' 'PLAYER_NAME=Marian Devecka' '-e' 'PLAYER_RACE=Z' '-e' 'NTH_PLAYER=1' '-e' 'NUM_PLAYERS=2' '-e' 'GAME_NAME=GAME_C764DACE' '-e' 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx' '-e' 'GAME_TYPE=FREE_FOR_ALL' '-e' 'SPEED_OVERRIDE=10' '-e' 'HIDE_NAMES=0' '-e' 'TM_LOG_RESULTS=../logs/GAME_C764DACE_1_results.json' '-e' 'TM_LOG_FRAMETIMES=../logs/GAME_C764DACE_1_frames.csv' '-e' 'TM_SPEED_OVERRIDE=10' '-e' 'TM_ALLOW_USER_INPUT=0' '-e' 'EXIT_CODE_REALTIME_OUTED=2' '-e' 'BOT_NAME=Marian Devecka' '-e' 'BOT_FILE=KillerBot.dll' '-e' 'BOT_BWAPI=4.1.2' 'starcraft:game' '/app/play_bot.sh' '--headful'
2018-02-16 22:41:46 INFO scbw.docker[7389] launched BotPlayer:Marian Devecka:Z
2018-02-16 22:41:46 DEBUG scbw.docker[7389] container name 'GAME_C764DACE_1_Marian_Devecka'
2018-02-16 22:41:46 DEBUG scbw.docker[7389] container id '6fb126438025'
2018-02-16 22:41:46 DEBUG scbw.docker[7389] Checking if game has launched properly...
2018-02-16 22:41:47 ERROR scbw.cli[7389] Some containers exited prematurely, please check logs
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/cli.py", line 198, in main
    game_result = run_game(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/game.py", line 94, in run_game
    _wait_callback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/docker.py", line 388, in launch_game
    raise DockerException("Some containers exited prematurely, please check logs")
scbw.error.DockerException: Some containers exited prematurely, please check logs

**Comment by kant2002** [comment]
Here the information from the logs
```
$ docker logs 6f7c5da8be03ef85c120bd92ec2a1931c5fb038c24dc462ca7c59e7c83929f6d
+ '[' --headful == --headful ']'
+ IS_HEADFUL=1
+ LOG_BASENAME=GAME_B4EC5672_0_CherryPi
+ LOG_GAME=/app/logs/GAME_B4EC5672_0_CherryPi_game.log
+ LOG_BOT=/app/logs/GAME_B4EC5672_0_CherryPi_bot.log
+ BOT_TYPE=dll
++ date +%Y-%m-%d
+ DATE=2018-02-16
+ REPLAY_FILE=maps/replays/GAME_B4EC5672_0.rep
+ . play_common.sh
+ check_bot_requirements
+ '[' '!' -d /app/bots/CherryPi ']'
+ '[' '!' -f /app/bots/CherryPi/AI/BWEnv.dll ']'
+ '[' '!' -f /app/bots/CherryPi/BWAPI.dll ']'
+ '[' dll '!=' jar ']'
+ '[' dll '!=' exe ']'
+ '[' dll '!=' dll ']'
+ cp -r /app/bots/CherryPi/AI/. /app/sc/bwapi-data/AI
+ cp -r /app/bots/CherryPi/read/. /app/sc/bwapi-data/read
cp: '/app/bots/CherryPi/read/.' and '/app/sc/bwapi-data/read/.' are the same file
```

**Comment by kant2002** [comment]
Given the fact that container run following similar command

    2018-02-17 10:01:08 DEBUG scbw.docker[6736] 'docker' 'run' '-d' '--privileged' 
    '--name' 'GAME_52458925_0_CherryPi' 
    '--volume' '//c/Users/user/AppData/Roaming/scbw/logs:/app/logs:rw' 

    // Looks here first, this folder is read only
    *'--volume' '//c/Users/user/AppData/Roaming/scbw/bots:/app/bots:ro'*

    '--volume' '//c/Users/user/AppData/Roaming/scbw/maps:/app/sc/maps:rw' 
    '--volume' '//c/Users/user/AppData/Roaming/scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw'
    '--volume' '//c/Users/user/AppData/Roaming/scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw' 
    '--net' 'sc_net' '-p' '5900:5900' 
    '--volume' '//c/Users/user/AppData/Roaming/scbw/bots/CherryPi/write/GAME_52458925_0:/app/sc/bwapi-data/write:rw' 
   
    // Looks here as well. Read folder is read write.
    '--volume' '//c/Users/user/AppData/Roaming/scbw/bots/CherryPi/read/:/app/sc/bwapi-data/read:rw' 
    '-e' 'PLAYER_NAME=CherryPi' '-e' 'PLAYER_RACE=Z' '-e' 'NTH_PLAYER=0' '-e' 'NUM_PLAYERS=2' '-e' 'GAME_NAME=GAME_52458925' '-e' 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx' '-e' 'GAME_TYPE=FREE_FOR_ALL' '-e' 'SPEED_OVERRIDE=10' '-e' 'HIDE_NAMES=0' '-e' 'TM_LOG_RESULTS=../logs/GAME_52458925_0_results.json' '-e' 'TM_LOG_FRAMETIMES=../logs/GAME_52458925_0_frames.csv' '-e' 'TM_SPEED_OVERRIDE=10' '-e' 'TM_ALLOW_USER_INPUT=0' '-e' 'EXIT_CODE_REALTIME_OUTED=2' '-e' 'BOT_NAME=CherryPi' '-e' 'BOT_FILE=BWEnv.dll' '-e' 'BOT_BWAPI=4.2.0' 'starcraft:game' '/app/play_bot.sh' '--headful'
```

**Comment by michalsustr** [comment]
Try `0.2b7`

**Comment by MicroDK** [comment]
`0.2b7`works!

**Comment by michalsustr** [comment]
@haopan27 do you still have this issue?

**Comment by haopan27** [comment]
No, I don't have this issue 'Some containers exited prematurely, please check logs' anymore (hooray to 0.2b7 :D), but got the following error message ('could not launch BotPlayer: '). Should I start a new issue thread?

scbw.play --bots Iron Hao --headless --log_level=DEBUG
DEBUG checking bot in C:\Users\fractal\AppData\Roaming/scbw/bots/Iron
DEBUG Starting new HTTP connection (1): sscaitournament.com
DEBUG http://sscaitournament.com:80 "GET /api/bots.php HTTP/1.1" 301 None
DEBUG Starting new HTTPS connection (1): sscaitournament.com
DEBUG https://sscaitournament.com:443 "GET /api/bots.php HTTP/1.1" 200 None
INFO Could not find Iron, trying to find closest match in 189 available bots
INFO Found these bots:
INFO 0: Stone
INFO 1: Korean
INFO 2: ggBot
INFO 3: Iron bot
INFO 4: If Bot
INFO Which would you like to use? (enter number 0-4)
3
DEBUG checking bot in C:\Users\fractal\AppData\Roaming/scbw/bots/Hao
DEBUG Starting new HTTP connection (1): sscaitournament.com
DEBUG http://sscaitournament.com:80 "GET /api/bots.php HTTP/1.1" 301 None
DEBUG Starting new HTTPS connection (1): sscaitournament.com
DEBUG https://sscaitournament.com:443 "GET /api/bots.php HTTP/1.1" 200 None
INFO Could not find Hao, trying to find closest match in 189 available bots
INFO Found these bots:
INFO 0: ggBot
INFO 1: Stone
INFO 2: Flash
INFO 3: Hao Pan
INFO 4: bftjoe
INFO Which would you like to use? (enter number 0-4)
3
DEBUG checking docker-machine presence
DEBUG Using docker machine version version 0.12.2, build 9371605
Error: No machine name(s) specified and no "default" machine exists
DEBUG Docker machine not present
DEBUG Using vnc host 'localhost'
DEBUG 'docker' 'run' '-d' '--privileged' '--name' 'GAME_38D22A47_0_Iron_bot' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/logs:/app/logs:rw' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/bots:/app/bots:ro' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/maps:/app/sc/maps:rw' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw' '--net' 'sc_net' '--volume' '//c/Users/fractal/AppData/Roaming/scbw/bots/Iron bot/write/GAME_38D22A47_0:/app/sc/bwapi-data/write:rw' '-e' 'PLAYER_NAME=Iron bot' '-e' 'PLAYER_RACE=T' '-e' 'NTH_PLAYER=0' '-e' 'NUM_PLAYERS=2' '-e' 'GAME_NAME=GAME_38D22A47' '-e' 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx' '-e' 'GAME_TYPE=FREE_FOR_ALL' '-e' 'SPEED_OVERRIDE=0' '-e' 'HIDE_NAMES=0' '-e' 'TM_LOG_RESULTS=../logs/GAME_38D22A47_0_results.json' '-e' 'TM_LOG_FRAMETIMES=../logs/GAME_38D22A47_0_frames.csv' '-e' 'TM_SPEED_OVERRIDE=0' '-e' 'TM_ALLOW_USER_INPUT=0' '-e' 'EXIT_CODE_REALTIME_OUTED=2' '-e' 'BOT_NAME=Iron bot' '-e' 'BOT_FILE=Iron.dll' '-e' 'BOT_BWAPI=4.1.2' 'starcraft:game' '/app/play_bot.sh' '--game' 'GAME_38D22A47' '--name' 'Iron bot' '--race' 'T' '--lan' '--host' '--map' '/app/sc/maps/sscai/(2)Benzene.scx'
Unable to find image 'starcraft:game' locally
docker: Error response from daemon: pull access denied for starcraft, repository does not exist or may require 'docker login'.
See 'docker run --help'.
ERROR could not launch BotPlayer:Iron bot:T in container GAME_38D22A47_0_Iron_bot
Traceback (most recent call last):
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\cli.py", line 198, in main
    game_result = run_game(args)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\game.py", line 94, in run_game
    _wait_callback)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\docker.py", line 389, in launch_game
    launch_image(player, nth_player=i, num_players=len(players), **launch_params)
  File "c:\users\fractal\appdata\local\programs\python\python36\lib\site-packages\scbw\docker.py", line 351, in launch_image
    f"could not launch {player} in container {container_name}")
scbw.error.DockerException: could not launch BotPlayer:Iron bot:T in container GAME_38D22A47_0_Iron_bot

**Comment by kant2002** [comment]
Looks like you should run `scbw.play --install` after install version greater then 0.2b4 (?not sure about exact version)

**Comment by haopan27** [comment]
Thanks so much Andrey. The game can be started and finished successfully after doing scbw.play --install again. Previously I thought this command pip install scbw==0.2b7 was enough to update scbw.play.

This issue can be closed now.
