### ISSUE TITLE
 Bot uses unsupported version of BWAPI: 3.7.4. Supported versions are: 4.2.0, 4.1.2, 3.7.5

### ISSUE THREAD

**Issue by haopan27** [Games-and-Simulations/sc-docker#77]
### expected behaviour
A game with Sijia Xu as one player should run.

### actual behaviour
ERROR Bot uses unsupported version of BWAPI: 3.7.4. Supported versions are: 4.2.0, 4.1.2, 3.7.5

### steps to reproduce
scbw.play --bots "Iron bot" "Sijia Xu" --headless

Please run the command issued with  `--log_level=DEBUG --log_verbose` parameters and log:
PS C:\Users\Fractal_Admin> scbw.play --bots "Iron bot" "Sijia Xu" --log_level=DEBUG --log_verbose --headless
2018-05-25 12:35:07 DEBUG scbw.bot_storage[6432] checking bot in C:\Users\Fractal_Admin\AppData\Roaming/scbw/bots/Iron bot
2018-05-25 12:35:07 DEBUG scbw.bot_storage[6432] found bot in C:\Users\Fractal_Admin\AppData\Roaming/scbw/bots/Iron bot
2018-05-25 12:35:07 DEBUG scbw.bot_storage[6432] checking bot in C:\Users\Fractal_Admin\AppData\Roaming/scbw/bots/Sijia Xu
2018-05-25 12:35:07 DEBUG scbw.bot_storage[6432] found bot in C:\Users\Fractal_Admin\AppData\Roaming/scbw/bots/Sijia Xu
2018-05-25 12:35:07 ERROR scbw.cli[6432] Bot uses unsupported version of BWAPI: 3.7.4. Supported versions are: 4.2.0, 4.1.2, 3.7.5
Traceback (most recent call last):
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\cli.py", line 198, in main
    game_result = run_game(args)
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\game.py", line 56, in run_game
    players += retrieve_bots(args.bots, bot_storages)
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\bot_factory.py", line 12, in retrieve_bots
    maybe_bot = bot_storage.find_bot(bot_name)
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\bot_storage.py", line 28, in find_bot
    bot = BotPlayer(f_name)
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\player.py", line 76, in __init__
    self.bwapi_version = self._find_bwapi_version()
  File "c:\users\fractal_admin\appdata\local\programs\python\python36\lib\site-packages\scbw\player.py", line 178, in _find_bwapi_version
    % (version, ', '.join(supported_versions))))
scbw.error.PlayerException: Bot uses unsupported version of BWAPI: 3.7.4. Supported versions are: 4.2.0, 4.1.2, 3.7.5

### operating system
Windows 10 Pro

### docker version
output of command `docker version`:

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

### scbw version

output of command `scbw.play -v`

    0.2a10

**Comment by michalsustr** [comment]
As it says, 3.7.4 is not supported. Version is supported, if we have a functioning tournament module (TM) binary for it (which we don't have for 3.7.4). If you are interested in adding 3.7.4 support please submit PR for https://github.com/Games-and-Simulations/sc-tm

**Comment by haopan27** [comment]
I am not interested in adding 3.7.4, rather wanted to check if there was a newer version of sc-docker that supports it. To me there is little value adding 3.7.4 support as most bots use more advanced BWAPI. The issue can stay closed now.

**Comment by bmnielsen** [comment]
I've submitted a PR with 3.7.4 support: https://github.com/Games-and-Simulations/sc-docker/pull/82
